version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      BLOG_DB__URI: "postgresql://postgres:postgres@db:5432/${BLOG_DB:-blog}"
      BLOG_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
   build: postgres
   image: blog_postgres-13-alpine-multi-user
   volumes:
     - $HOME/.postgres/blog_db/data/postgresql:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   environment:
   - POSTGRES_DB=blog, blog_test
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres